### ISSUE TITLE
Package.json changes

### ISSUE THREAD

**Issue by msholly** [paulsutherland/Polyonic#1]
Using Ionic, Electron and your plans to eventually support Office 365 builds really interested me. 

I had a few issues starting up the project, and I think this might be a helpful change. 

`    "dev": "cd src && gulp dev",
`

Should the package.json on the root have `&&` instead if semi-colons? We want to run the second command if the first is successful, using this article as reference: 
https://blog.jayway.com/2014/03/28/running-scripts-with-npm/

Let me know if this helps, or you're looking for help on this project otherwise. Thanks.

**Comment by paulsutherland** [comment]
@msholly 

Thanks, yes good catch there.  I use the fish terminal, which uses semicolons as opposed to ampersands for splitting commands!

I have updated package.json to include the double ampersands for scripts that execute multiple commands.

I already have office 365 running inside of the Polyonic setup, but the login process is a bit flaky.  This was due to Ionic now pushing their Nav stack as opposed to being able to link/map to URLs.  This made the authentication processes a bit difficult.  I had to mangle the use of a webview to login and get the azure and graph tokens.  The MS-Adal plugin for Cordova is great, but you have to do it manually in electron!

Anyway, I noticed yesterday that Ionic have the [deeplinker](https://ionicframework.com/docs/v2/api/navigation/DeepLinker/) in the api now, so I will update my office 365 example.

When I get it finished I will drop you a line.

Cheers..

Paul

**Comment by msholly** [comment]
Awesome, you have a tester if you need one. Thanks for your work.
