### ISSUE TITLE
Flat src folder structue

### ISSUE THREAD

**Issue by garhbod** [paulsutherland/Polyonic#16]
Do you think it would be at all possible to pull ionic out of the src folder to make it a single src folder rather than a src folder containing a whole other repo essentially.

If not should this actually be seperated into 2 repo?

**Comment by paulsutherland** [comment]
Hi, sorry for the delay responding, I was on a summer holiday.

When I first put the repo together I wanted to always pull in the latest ionic release, as in when you ran `npm start` it would download the latest ionic build into the src directory.

This was running fine until ionic moved away from gulp to ionic-app-scripts.  I was able to run the scripts in the top level directory until about version 0.0.38. In this release they hard coded the paths which meant I could not call ionic-app-scripts from the top level, outside the src folder.  This meant I had to place the gulp live reload script for electron in the src directory, as well as the app.js file for serving the files.

This meant that the src folder was no longer housing a vanilla ionic build.

I always intended on revisiting this once ionic-app-scripts had settled down, as they were jumping from rollup to webpack and making a lot of changes in each release during the Ionic 2 beta release phase.

I do mull the idea over as to the best way to structure it every time I update the repo.  And here are a few things I am taking into consideration:

- It would not really be of a benefit in a separate repo as it is only really of use in this Polyonic app. outside of this project, you would just use Ionic.
- If ionic create a release with breaking changes, it will break this repo without warning, but I could pin it of course.
- I would need to create a config folder to move a copy of the app.js and gulpfile.js files into the src folder, and update the ionic package.json file with the electron packages and the osx build info on each new build.

I was ok with manually updating the repo with each new Ionic release as it allowed me to understand what they had updated and to test everything out and make sure it was working, but since the repo is gaining a bit more interest and traffic, I will look into updating electron build and see if i can get it to pull the latest ionic release.

I am not precious on how it is structured, I wanted it to be a complete repo so people could understand what additions were added on top of ionic to get electron working. So I am open to suggestions on what people think is a better structure.

Thanks,

Paul
