### ISSUE TITLE
Ionic Native

### ISSUE THREAD

**Issue by tetpsy** [paulsutherland/Polyonic#23]
Hi there

Great work.

Does Polyonic support Ionic Native?
I would think that it doesnt.

Thanks

**Comment by paulsutherland** [comment]
@tetpsy 

Hi, since it is a wrapper around Ionic, it supports Ionic Native when building for native mobile only.  Just as you would with a standard Ionic native mobile app.

When Ionic 4 comes out with Capacitor, there will be some reach into electron and web apps, but for now you would need to rely on the web apis for those platforms.

Cheers..

Paul
