### ISSUE TITLE
Live Reload

### ISSUE THREAD

**Issue by rlaurente** [paulsutherland/Polyonic#35]
Is there a way to make main process files do live reload too ?

Thanks

**Comment by paulsutherland** [comment]
@rlaurente 

Yes, I have pushed an update:

`git pull`

I have changed the npm script for debugging the main process:

`npm run electron:dev:debug-main`

This will allow you to reload both the main process and changes in the app. It requires Chrome to be installed and open to run the main process debugger.

Thanks,

Paul

**Comment by rlaurente** [comment]
that was fast. will check

thanks

**Comment by rlaurente** [comment]
after pulling updates, npm install and running the app using npm run electron:dev:debug-main
The app didn't start and the icon keeps jumping in my mac's dock  like it's freezing. It's same scenario with npm run electron:dev:debug
btw, I'm using mac mojave.

Thanks

**Comment by paulsutherland** [comment]
Ok. What happens if you have Chrome open, does it launch ok then?

**Comment by rlaurente** [comment]
Same issue and btw it's also happening in npm run electron:dev:debug. I just closed that issue because I found easier fix setting electron env variable ELECTRON_ENABLE_LOGGING = true. Please refer screenshot.

thanks


![Screen Shot 2019-09-17 at 11 11 24 PM](https://user-images.githubusercontent.com/1804380/65054713-96d44800-d9a0-11e9-879a-f60ecdcd5c65.png)

**Comment by paulsutherland** [comment]
Ok thanks. I’ll look into that in the morning. I should have put that on a branch until it was tested.

In the meantime you’ll have to revert a commit to continue using the app.

I’ll let you know when I am done.

Cheers...

Paul

**Comment by paulsutherland** [comment]
@rlaurente 

I had a chance to work through this today.

The issue is you need to attach the debugger to the process.  I have updated the docs and include below the extract that hopefully explains how to get a live reloading session when debugging the main process.

## Running live reload for development

When developing, you will want to have the app live reload as you save your changes.

### Desktop

```node
npm run electron:dev
```

For debugging the main process you will need to have the Chrome Browser installed.

```node
npm run electron:dev:debug
```

Open Chrome and navigate to chrome://inspect/ and select the Electron remote target that is available to attach the debugger to.

If you require live reloading of the main process debugging session, then it is recommended that you install the Chrome plugin [Node.js V8 --inspector Manager (NiM)](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj?hl=en). In the plugin settings, set the host to localhost, the port to 9229 and the app to auto.  This will allow you to live reload changes made to the main process (electron.js file).

```node
npm run electron:dev:debug-live
```
