### ISSUE TITLE
How do you call main process methods from within angular component with this setup?

### ISSUE THREAD

**Issue by PabloWestphalen** [paulsutherland/Polyonic#5]
Can't find a way to get a working reference to electron.remote

**Comment by paulsutherland** [comment]
@PabloWestphalen 

Hi,

I have committed a change that includes a reference to electron and electron remote. I must have dropped the example out of the template when upgrading Ionic versions.

It has been a while since I visited this, but getting node and electron to work in Typescript was a pain, so I inserted my requires for electron and path in index.html, just below the Cordova import. The idea being you toggle the comments to suit the platform you are targeting. 

**Index.html:**

```
...
  **MOBILE**
  <!-- cordova.js required for cordova apps -->
  <!--<script src="cordova.js"></script>-->

 **DESKTOP**
  <!-- un-comment this code for Node.JS integration in Ionic for Electron, we load the Node packages here-->
  <script>
      const electron  = require('electron');
      const path      = require('path');
  </script>

 **PROGRESSIVE WEB APP**
  <!-- un-comment this code to enable service worker
  <script>
    if ('serviceWorker' in navigator) {
      navigator.serviceWorker.register('service-worker.js')
        .then(() => console.log('service worker installed'))
        .catch(err => console.error('Error', err));
    }
  </script>-->
...
```
Then you declare them in your page class, or provider:

home.ts
```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

declare const electron
declare const path

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {
    console.log('Electron is now available: ', electron)
    console.log('Electron remote is now available: ', electron.remote)
    console.log('Path is now available: ', path)
  }

}
```

That was the only way I could get node to talk to the file system and electron.  As I say, it has been a while and I need to revisit this to see if I can do better with the integration, but I recall webpack and rollup gave me a lot of headaches when bundling and compiling typescript, I just could not get node to work as node does not play happily with imports.

Any other node packages you require for your project, again you include them in the same way, then declare them in your classes.

Hope that helps.
