### ISSUE TITLE
Issue running npm start on Ubuntu

### ISSUE THREAD

**Issue by ycarriger** [paulsutherland/Polyonic#8]
Gulp tasks throw error on Ubuntu, unable to proceed further.
Traced to issue here: https://github.com/BrowserSync/browser-sync/issues/224

Solution (as stated there by amoswachanga ) is to run the following cmd in a Terminal session:
echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

This resolved the issue for me.

**Comment by paulsutherland** [comment]
I will investigate this with issue #11

**Comment by paulsutherland** [comment]
Hi @ycarriger,

I worked through some Ubuntu issues #8 #11 and confirm that this issue is related to the file watchers limit in Ubuntu.  [The resolution is to increase the number of file watchers to allow gulp to run](https://stackoverflow.com/questions/22475849/node-js-error-enospc).

But you knew that anyway 😄 

I have updated the README to inform Ubuntu users to increase this limit to allow them to run the app in dev/livereload mode.

Many thanks for the feedback 👍
